'use strict';
const TASKS = [
  { id: 'T001', difficulty: { 3: 2, 4: 3, 5: 3 }, type: 'trickCountMoreThanAllOthers', params: {},
    text: 'owner가 다른 모든 개별 플레이어보다 더 많은 트릭을 획득한다.' },
  { id: 'T002', difficulty: { 3: 3, 4: 4, 5: 5 }, type: 'trickCountMoreThanSumOthers', params: {},
    text: 'owner가 다른 플레이어들이 획득한 트릭 수의 합보다 더 많은 트릭을 획득한다.' },
  { id: 'T003', difficulty: { 3: 2, 4: 2, 5: 3 }, type: 'trickCountFewerThanAllOthers', params: {},
    text: 'owner가 다른 모든 개별 플레이어보다 더 적은 트릭을 획득한다.' },
  { id: 'T004', difficulty: { 3: 2, 4: 2, 5: 3 }, type: 'trickCountMoreThanCaptain', params: {}, captainCannotOwn: true,
    text: 'owner가 선장보다 더 많은 트릭을 획득한다. (선장은 선택 불가)' },
  { id: 'T005', difficulty: { 3: 2, 4: 2, 5: 2 }, type: 'trickCountFewerThanCaptain', params: {}, captainCannotOwn: true,
    text: 'owner가 선장보다 더 적은 트릭을 획득한다. (선장은 선택 불가)' },
  { id: 'T006', difficulty: { 3: 4, 4: 3, 5: 3 }, type: 'trickCountEqualCaptain', params: {}, captainCannotOwn: true,
    text: 'owner와 선장이 같은 수의 트릭을 획득한다. (선장은 선택 불가)' },
  { id: 'T007', difficulty: { 3: 2, 4: 3, 5: 3 }, type: 'trickAllColorValuesUnder', params: { under: 7 },
    text: 'owner가 모든 일반 색상 카드의 값이 7 미만인 트릭을 획득한다. (잠수함 포함 시 실패)' },
  { id: 'T008', difficulty: { 3: 2, 4: 3, 5: 4 }, type: 'trickAllColorValuesOver', params: { over: 5 },
    text: 'owner가 모든 일반 색상 카드의 값이 5 초과인 트릭을 획득한다. (잠수함 포함 시 실패)' },
  { id: 'T009', difficulty: { 3: 2, 4: 3, 5: 3 }, type: 'trickContainsColorValue', params: { value: 6 },
    text: 'owner가 네 색상 중 숫자 6 카드가 포함된 트릭을 획득한다.' },
  { id: 'T010', difficulty: { 3: 2, 4: 3, 5: 4 }, type: 'trickContainsColorValue', params: { value: 5 },
    text: 'owner가 네 색상 중 숫자 5 카드가 포함된 트릭을 획득한다.' },
  { id: 'T011', difficulty: { 3: 3, 4: 4, 5: 5 }, type: 'trickContainsColorValue', params: { value: 3 },
    text: 'owner가 네 색상 중 숫자 3 카드가 포함된 트릭을 획득한다.' },
  { id: 'T012', difficulty: { 3: 1, 4: 2, 5: 2 }, type: 'winningCardCapturesCard', params: { winValue: 7, capturedValue: 5 },
    text: 'owner가 일반 색상 7을 승리 카드로 사용하여 같은 트릭의 일반 색상 5를 획득한다.' },
  { id: 'T013', difficulty: { 3: 3, 4: 4, 5: 5 }, type: 'winningCardCapturesCard', params: { winValue: 4, capturedValue: 8 },
    text: 'owner가 일반 색상 4를 승리 카드로 사용하여 같은 트릭의 일반 색상 8을 획득한다.' },
  { id: 'T014', difficulty: { 3: 2, 4: 3, 5: 4 }, type: 'trickContainsCountOfNumber', params: { value: 6, count: 2 },
    text: 'owner가 서로 다른 두 장의 일반 색상 6이 포함된 트릭을 획득한다.' },
  { id: 'T015', difficulty: { 3: 3, 4: 4, 5: 5 }, type: 'trickContainsColorValue', params: { value: 2 },
    text: 'owner가 네 색상 중 숫자 2 카드가 포함된 트릭을 획득한다.' },
  { id: 'T016', difficulty: { 3: 1, 4: 1, 5: 1 }, type: 'acquireSpecificCard', params: { suit: 'PINK', value: 3 },
    text: 'owner가 PINK 3을 획득한다.' },
  { id: 'T017', difficulty: { 3: 1, 4: 1, 5: 1 }, type: 'acquireSpecificCard', params: { suit: 'YELLOW', value: 1 },
    text: 'owner가 YELLOW 1을 획득한다.' },
  { id: 'T018', difficulty: { 3: 1, 4: 1, 5: 1 }, type: 'acquireSpecificCard', params: { suit: 'BLUE', value: 4 },
    text: 'owner가 BLUE 4를 획득한다.' },
  { id: 'T019', difficulty: { 3: 1, 4: 1, 5: 1 }, type: 'acquireSpecificCard', params: { suit: 'GREEN', value: 6 },
    text: 'owner가 GREEN 6을 획득한다.' },
  { id: 'T020', difficulty: { 3: 3, 4: 4, 5: 5 }, type: 'acquireAllOfNumber', params: { value: 3 },
    text: 'owner가 네 색상의 숫자 3을 모두 획득한다.' },
  { id: 'T021', difficulty: { 3: 3, 4: 4, 5: 5 }, type: 'acquireAtLeastOfNumber', params: { value: 5, count: 3 },
    text: 'owner가 네 색상의 숫자 5 중 최소 3장을 획득한다.' },
  { id: 'T022', difficulty: { 3: 3, 4: 4, 5: 5 }, type: 'acquireAtLeastOfNumber', params: { value: 9, count: 3 },
    text: 'owner가 네 색상의 숫자 9 중 최소 3장을 획득한다.' },
  { id: 'T023', difficulty: { 3: 2, 4: 2, 5: 2 }, type: 'acquireAtLeastOfNumber', params: { value: 7, count: 2 },
    text: 'owner가 네 색상의 숫자 7 중 최소 2장을 획득한다.' },
  { id: 'T024', difficulty: { 3: 4, 4: 5, 5: 6 }, type: 'acquireAllOfNumber', params: { value: 9 },
    text: 'owner가 네 색상의 숫자 9를 모두 획득한다.' },
  { id: 'T025', difficulty: { 3: 4, 4: 5, 5: 4 }, type: 'acquireExactlyOfNumber', params: { value: 6, count: 3 },
    text: 'owner가 네 색상의 숫자 6을 정확히 3장 획득한다.' },
  { id: 'T026', difficulty: { 3: 2, 4: 3, 5: 3 }, type: 'acquireExactlyOfNumber', params: { value: 9, count: 2 },
    text: 'owner가 네 색상의 숫자 9를 정확히 2장 획득한다.' },
  { id: 'T027', difficulty: { 3: 2, 4: 3, 5: 3 }, type: 'acquireMultipleSpecificCards',
    params: { cards: [{ suit: 'BLUE', value: 1 }, { suit: 'BLUE', value: 2 }, { suit: 'BLUE', value: 3 }] },
    text: 'owner가 BLUE 1, BLUE 2, BLUE 3을 모두 획득한다.' },
  { id: 'T028', difficulty: { 3: 2, 4: 2, 5: 3 }, type: 'acquireMultipleSpecificCards',
    params: { cards: [{ suit: 'BLUE', value: 6 }, { suit: 'YELLOW', value: 7 }] },
    text: 'owner가 BLUE 6과 YELLOW 7을 모두 획득한다.' },
  { id: 'T029', difficulty: { 3: 2, 4: 2, 5: 3 }, type: 'acquireMultipleSpecificCards',
    params: { cards: [{ suit: 'PINK', value: 5 }, { suit: 'YELLOW', value: 6 }] },
    text: 'owner가 PINK 5와 YELLOW 6을 모두 획득한다.' },
  { id: 'T030', difficulty: { 3: 2, 4: 2, 5: 3 }, type: 'acquireMultipleSpecificCards',
    params: { cards: [{ suit: 'GREEN', value: 5 }, { suit: 'BLUE', value: 8 }] },
    text: 'owner가 GREEN 5와 BLUE 8을 모두 획득한다.' },
  { id: 'T031', difficulty: { 3: 2, 4: 2, 5: 3 }, type: 'acquireMultipleSpecificCards',
    params: { cards: [{ suit: 'BLUE', value: 5 }, { suit: 'PINK', value: 8 }] },
    text: 'owner가 BLUE 5와 PINK 8을 모두 획득한다.' },
  { id: 'T032', difficulty: { 3: 2, 4: 2, 5: 3 }, type: 'acquireMultipleSpecificCards',
    params: { cards: [{ suit: 'PINK', value: 9 }, { suit: 'YELLOW', value: 8 }] },
    text: 'owner가 PINK 9와 YELLOW 8을 모두 획득한다.' },
  { id: 'T033', difficulty: { 3: 2, 4: 2, 5: 2 }, type: 'acquireMultipleSpecificCards',
    params: { cards: [{ suit: 'PINK', value: 1 }, { suit: 'GREEN', value: 7 }] },
    text: 'owner가 PINK 1과 GREEN 7을 모두 획득한다.' },
  { id: 'T034', difficulty: { 3: 2, 4: 3, 5: 3 }, type: 'acquireMultipleSpecificCards',
    params: { cards: [{ suit: 'YELLOW', value: 9 }, { suit: 'BLUE', value: 7 }] },
    text: 'owner가 YELLOW 9와 BLUE 7을 모두 획득한다.' },
  { id: 'T035', difficulty: { 3: 3, 4: 4, 5: 4 }, type: 'acquireMultipleSpecificCards',
    params: { cards: [{ suit: 'GREEN', value: 3 }, { suit: 'YELLOW', value: 4 }, { suit: 'YELLOW', value: 5 }] },
    text: 'owner가 GREEN 3, YELLOW 4, YELLOW 5를 모두 획득한다.' },
  { id: 'T036', difficulty: { 3: 3, 4: 4, 5: 5 }, type: 'acquireSpecificCardInTrick',
    params: { suit: 'GREEN', value: 2, trick: 'last' },
    text: 'owner가 GREEN 2를 마지막 트릭에서 획득한다.' },
  { id: 'T037', difficulty: { 3: 4, 4: 4, 5: 4 }, type: 'colorCountExactMulti',
    params: { counts: { PINK: 1, GREEN: 1 } },
    text: '임무 종료 시 owner가 획득한 카드 중 PINK가 정확히 1장이고 GREEN이 정확히 1장이다. (다른 색상/잠수함 제한 없음)' },
  { id: 'T038', difficulty: { 3: 3, 4: 3, 5: 3 }, type: 'colorCountAtLeast', params: { suit: 'YELLOW', count: 7 },
    text: 'owner가 YELLOW를 최소 7장 획득한다.' },
  { id: 'T039', difficulty: { 3: 2, 4: 3, 5: 3 }, type: 'colorCountAtLeast', params: { suit: 'PINK', count: 5 },
    text: 'owner가 PINK를 최소 5장 획득한다.' },
  { id: 'T040', difficulty: { 3: 3, 4: 4, 5: 4 }, type: 'colorCountExact', params: { suit: 'GREEN', count: 2 },
    text: 'owner가 GREEN을 정확히 2장 획득한다.' },
  { id: 'T041', difficulty: { 3: 3, 4: 4, 5: 4 }, type: 'colorCountExact', params: { suit: 'BLUE', count: 2 },
    text: 'owner가 BLUE를 정확히 2장 획득한다.' },
  { id: 'T042', difficulty: { 3: 3, 4: 3, 5: 4 }, type: 'colorCountExact', params: { suit: 'PINK', count: 1 },
    text: 'owner가 PINK를 정확히 1장 획득한다.' },
  { id: 'T043', difficulty: { 3: 2, 4: 2, 5: 2 }, type: 'colorCountExact', params: { suit: 'PINK', count: 0 },
    text: 'owner가 PINK를 한 장도 획득하지 않는다.' },
  { id: 'T044', difficulty: { 3: 2, 4: 3, 5: 4 }, type: 'acquireAtLeastOnePerColorAll', params: {},
    text: 'owner가 네 일반 색상 각각을 최소 1장씩 획득한다. (잠수함 제외)' },
  { id: 'T045', difficulty: { 3: 3, 4: 4, 5: 5 }, type: 'acquireFullRunOneColor', params: {},
    text: 'owner가 네 색상 중 최소 한 색상의 1~9 전체를 획득한다. (잠수함 제외)' },
  { id: 'T046', difficulty: { 3: 2, 4: 5, 5: 6 }, type: 'trickAllValuesEven', params: {},
    text: 'owner가 모든 카드 값이 짝수(2,4,6,8)인 트릭을 획득한다. (잠수함 포함 시 실패)' },
  { id: 'T047', difficulty: { 3: 2, 4: 4, 5: 5 }, type: 'trickAllValuesOdd', params: {},
    text: 'owner가 모든 카드 값이 홀수(1,3,5,7,9)인 트릭을 획득한다. (잠수함 포함 시 실패)' },
  { id: 'T048', difficulty: { 3: 3, 4: 3, 5: 4 }, type: 'trickColorSumOver', params: { threshold: { 3: 23, 4: 28, 5: 31 } },
    text: 'owner가 일반 색상 카드 값 합계가 기준(3인 23/4인 28/5인 31) 초과인 트릭을 획득한다. (잠수함 포함 시 실패)' },
  { id: 'T049', difficulty: { 3: 3, 4: 3, 5: 4 }, type: 'trickColorSumUnder', params: { threshold: { 3: 8, 4: 12, 5: 16 } },
    text: 'owner가 일반 색상 카드 값 합계가 기준(3인 8/4인 12/5인 16) 미만인 트릭을 획득한다. (잠수함 포함 시 실패)' },
  { id: 'T050', difficulty: { 3: 3, 4: 3, 5: 4 }, type: 'trickColorSumIn', params: { values: [22, 23] },
    text: 'owner가 일반 색상 카드 값 합계가 22 또는 23인 트릭을 획득한다. (잠수함 포함 시 실패)' },
  { id: 'T051', difficulty: { 3: 3, 4: 3, 5: 3 }, type: 'submarineCountExact', params: { count: 1, redistributeIfAllFourToOnePlayer: true },
    text: 'owner가 잠수함을 정확히 1장 획득한다. (한 플레이어가 잠수함 4장을 모두 받으면 재분배, 실패로 계산하지 않음)' },
  { id: 'T052', difficulty: { 3: 3, 4: 3, 5: 3 }, type: 'submarineExactAndOnly',
    params: { mainValue: 1, redistributeIfTogether: [4], redistributeIfAllOf: [1, 2, 3] },
    text: 'owner가 잠수함 1을 획득하고 다른 잠수함은 획득하지 않는다. (1&4 동시 소지 또는 1,2,3 모두 소지 시 재분배)' },
  { id: 'T053', difficulty: { 3: 3, 4: 3, 5: 3 }, type: 'submarineExactAndOnly',
    params: { mainValue: 2, redistributeIfTogether: [4], redistributeIfAllOf: [1, 2, 3] },
    text: 'owner가 잠수함 2를 획득하고 다른 잠수함은 획득하지 않는다. (2&4 동시 소지 또는 1,2,3 모두 소지 시 재분배)' },
  { id: 'T054', difficulty: { 3: 1, 4: 1, 5: 1 }, type: 'acquireSpecificCard', params: { suit: 'SUBMARINE', value: 3 },
    text: 'owner가 잠수함 3을 획득한다.' },
  { id: 'T055', difficulty: { 3: 3, 4: 3, 5: 4 }, type: 'submarineCountExact', params: { count: 2, redistributeIfAllOf: [2, 3, 4] },
    text: 'owner가 잠수함을 정확히 2장 획득한다. (2,3,4 모두 한 사람이 가지면 재분배)' },
  { id: 'T056', difficulty: { 3: 3, 4: 4, 5: 4 }, type: 'submarineCountExact', params: { count: 3, redistributeIfAllFourToOnePlayer: true },
    text: 'owner가 잠수함을 정확히 3장 획득한다. (한 플레이어가 잠수함 4장을 모두 가지면 재분배)' },
  { id: 'T057', difficulty: { 3: 1, 4: 1, 5: 1 }, type: 'submarineCountExact', params: { count: 0 },
    text: 'owner가 잠수함을 한 장도 획득하지 않는다.' },
  { id: 'T058', difficulty: { 3: 3, 4: 3, 5: 3 }, type: 'winSubmarineTrickWithCard', params: { suit: 'PINK', value: 7 },
    text: 'owner가 잠수함을 직접 내어 승리한 트릭에서 PINK 7을 획득한다.' },
  { id: 'T059', difficulty: { 3: 3, 4: 3, 5: 3 }, type: 'winSubmarineTrickWithCard', params: { suit: 'GREEN', value: 9 },
    text: 'owner가 잠수함을 직접 내어 승리한 트릭에서 GREEN 9를 획득한다.' },
  { id: 'T060', difficulty: { 3: 4, 4: 3, 5: 3 }, type: 'neverLeadWithSuits', params: { suits: ['PINK', 'YELLOW', 'BLUE'] },
    text: 'owner는 어떤 트릭도 PINK, YELLOW, BLUE로 시작하지 않는다. (GREEN, SUBMARINE 시작은 허용)' },
  { id: 'T061', difficulty: { 3: 2, 4: 1, 5: 1 }, type: 'neverLeadWithSuits', params: { suits: ['PINK', 'GREEN'] },
    text: 'owner는 어떤 트릭도 PINK 또는 GREEN으로 시작하지 않는다. (BLUE, YELLOW, SUBMARINE 시작은 허용)' },
  { id: 'T062', difficulty: { 3: 2, 4: 2, 5: 2 }, type: 'colorCountExact', params: { suit: 'GREEN', count: 0 },
    text: 'owner가 GREEN을 한 장도 획득하지 않는다.' },
  { id: 'T063', difficulty: { 3: 2, 4: 2, 5: 2 }, type: 'colorCountExact', params: { suit: 'YELLOW', count: 0 },
    text: 'owner가 YELLOW를 한 장도 획득하지 않는다.' },
  { id: 'T064', difficulty: { 3: 3, 4: 3, 5: 3 }, type: 'colorCountExactMulti', params: { counts: { PINK: 0, BLUE: 0 } },
    text: 'owner가 PINK와 BLUE를 한 장도 획득하지 않는다.' },
  { id: 'T065', difficulty: { 3: 3, 4: 3, 5: 3 }, type: 'colorCountExactMulti', params: { counts: { YELLOW: 0, GREEN: 0 } },
    text: 'owner가 YELLOW와 GREEN을 한 장도 획득하지 않는다.' },
  { id: 'T066', difficulty: { 3: 3, 4: 3, 5: 2 }, type: 'numberCountExactMulti', params: { counts: { 8: 0, 9: 0 } },
    text: 'owner가 네 색상의 숫자 8과 숫자 9를 한 장도 획득하지 않는다.' },
  { id: 'T067', difficulty: { 3: 1, 4: 1, 5: 1 }, type: 'numberCountExact', params: { value: 9, count: 0 },
    text: 'owner가 네 색상의 숫자 9를 한 장도 획득하지 않는다.' },
  { id: 'T068', difficulty: { 3: 1, 4: 2, 5: 2 }, type: 'numberCountExact', params: { value: 5, count: 0 },
    text: 'owner가 네 색상의 숫자 5를 한 장도 획득하지 않는다.' },
  { id: 'T069', difficulty: { 3: 2, 4: 2, 5: 2 }, type: 'numberCountExact', params: { value: 1, count: 0 },
    text: 'owner가 네 색상의 숫자 1을 한 장도 획득하지 않는다.' },
  { id: 'T070', difficulty: { 3: 3, 4: 3, 5: 3 }, type: 'numberCountExactMulti', params: { counts: { 1: 0, 2: 0, 3: 0 } },
    text: 'owner가 네 색상의 숫자 1, 2, 3을 한 장도 획득하지 않는다.' },
  { id: 'T071', difficulty: { 3: 1, 4: 2, 5: 3 }, type: 'noTricksInRange', params: { from: 1, to: 4 },
    text: 'owner가 첫 4개 트릭을 하나도 획득하지 않는다.' },
  { id: 'T072', difficulty: { 3: 1, 4: 2, 5: 2 }, type: 'noTricksInRange', params: { from: 1, to: 3 },
    text: 'owner가 첫 3개 트릭을 하나도 획득하지 않는다.' },
  { id: 'T073', difficulty: { 3: 2, 4: 3, 5: 3 }, type: 'noTricksInRange', params: { from: 1, to: 5 },
    text: 'owner가 첫 5개 트릭을 하나도 획득하지 않는다.' },
  { id: 'T074', difficulty: { 3: 4, 4: 3, 5: 3 }, type: 'noTricksAtAll', params: {},
    text: 'owner가 전체 임무에서 트릭을 하나도 획득하지 않는다.' },
  { id: 'T075', difficulty: { 3: 3, 4: 2, 5: 2 }, type: 'neverConsecutiveTricks', params: {},
    text: 'owner가 연속된 두 트릭을 획득하는 일이 없어야 한다.' },
  { id: 'T076', difficulty: { 3: 2, 4: 3, 5: 3 }, type: 'winSpecificTrick', params: { trick: 'last' },
    text: 'owner가 마지막 트릭을 획득한다.' },
  { id: 'T077', difficulty: { 3: 2, 4: 3, 5: 4 }, type: 'winTricks', params: { tricks: [1, 2, 3] },
    text: 'owner가 첫 번째, 두 번째, 세 번째 트릭을 모두 획득한다.' },
  { id: 'T078', difficulty: { 3: 1, 4: 1, 5: 2 }, type: 'winTricks', params: { tricks: [1, 2] },
    text: 'owner가 첫 번째와 두 번째 트릭을 모두 획득한다.' },
  { id: 'T079', difficulty: { 3: 1, 4: 1, 5: 1 }, type: 'winSpecificTrick', params: { trick: 1 },
    text: 'owner가 첫 번째 트릭을 획득한다.' },
  { id: 'T080', difficulty: { 3: 3, 4: 4, 5: 4 }, type: 'winTricks', params: { tricks: [1, 'last'] },
    text: 'owner가 첫 번째 트릭과 마지막 트릭을 모두 획득한다. (중간 트릭 획득 여부는 제한하지 않음)' },
  { id: 'T081', difficulty: { 3: 4, 4: 4, 5: 4 }, type: 'winOnlyTrick', params: { trick: 'last' },
    text: 'owner가 마지막 트릭만 획득한다. (그 외에는 어떤 트릭도 획득하면 안 됨)' },
  { id: 'T082', difficulty: { 3: 4, 4: 3, 5: 3 }, type: 'winOnlyTrick', params: { trick: 1 },
    text: 'owner가 첫 번째 트릭만 획득한다. (그 외에는 어떤 트릭도 획득하면 안 됨)' },
  { id: 'T083', difficulty: { 3: 3, 4: 2, 5: 2 }, type: 'winExactlyNTricks', params: { n: 1 },
    text: 'owner가 정확히 1개 트릭을 획득한다.' },
  { id: 'T084', difficulty: { 3: 2, 4: 2, 5: 2 }, type: 'winExactlyNTricks', params: { n: 2 },
    text: 'owner가 정확히 2개 트릭을 획득한다.' },
  { id: 'T085', difficulty: { 3: 1, 4: 1, 5: 1 }, type: 'consecutiveAtLeast', params: { n: 2 },
    text: 'owner가 연속된 트릭을 최소 2개 획득한다.' },
  { id: 'T086', difficulty: { 3: 2, 4: 3, 5: 4 }, type: 'consecutiveAtLeast', params: { n: 3 },
    text: 'owner가 연속된 트릭을 최소 3개 획득한다.' },
  { id: 'T087', difficulty: { 3: 2, 4: 3, 5: 5 }, type: 'winExactlyNTricks', params: { n: 4 },
    text: 'owner가 전체 임무에서 정확히 4개 트릭을 획득한다. (연속일 필요 없음)' },
  { id: 'T088', difficulty: { 3: 3, 4: 3, 5: 4 }, type: 'consecutiveExactRun', params: { n: 3 },
    text: 'owner가 정확히 3개로 구성된 연속 승리 구간을 만든다.' },
  { id: 'T089', difficulty: { 3: 3, 4: 3, 5: 3 }, type: 'consecutiveExactRun', params: { n: 2 },
    text: 'owner가 정확히 2개로 구성된 연속 승리 구간을 만든다.' },
  { id: 'T090', difficulty: { 3: 3, 4: 2, 5: 2 }, type: 'predictTrickCountOpen', params: {},
    text: '과제 배정 후 첫 트릭 전, owner가 획득할 트릭 수 X를 공개 선언한다. 종료 시 trickCount == X.' },
  { id: 'T091', difficulty: { 3: 4, 4: 3, 5: 3 }, type: 'predictTrickCountSecret', params: {},
    text: '과제 배정 후 첫 트릭 전, owner가 획득할 트릭 수 X를 비공개로 기록한다(변경 불가). 종료 후 공개해 trickCount == X 확인.' },
  { id: 'T092', difficulty: { 3: 4, 4: 4, 5: 4 }, type: 'colorCountEqualEndOfMission',
    params: { suitA: 'PINK', suitB: 'YELLOW', minEach: 1 },
    text: '임무 종료 시 owner가 획득한 PINK 수와 YELLOW 수가 같다 (둘 다 최소 1장 이상).' },
  { id: 'T093', difficulty: { 3: 2, 4: 3, 5: 3 }, type: 'colorCountEqualInSingleTrick',
    params: { suitA: 'GREEN', suitB: 'YELLOW', minEach: 1 },
    text: 'owner가 획득한 특정 한 트릭 안에서 GREEN 수와 YELLOW 수가 같다 (둘 다 최소 1장 이상).' },
  { id: 'T094', difficulty: { 3: 2, 4: 3, 5: 3 }, type: 'colorCountEqualInSingleTrick',
    params: { suitA: 'PINK', suitB: 'BLUE', minEach: 1 },
    text: 'owner가 획득한 특정 한 트릭 안에서 PINK 수와 BLUE 수가 같다 (둘 다 최소 1장 이상).' },
  { id: 'T095', difficulty: { 3: 1, 4: 1, 5: 1 }, type: 'colorCountGreaterEndOfMission',
    params: { suitA: 'YELLOW', suitB: 'BLUE' },
    text: '임무 종료 시 owner가 획득한 YELLOW 수가 BLUE 수보다 많다 (BLUE 0장도 허용).' },
  { id: 'T096', difficulty: { 3: 1, 4: 1, 5: 1 }, type: 'colorCountGreaterEndOfMission',
    params: { suitA: 'PINK', suitB: 'GREEN' },
    text: '임무 종료 시 owner가 획득한 PINK 수가 GREEN 수보다 많다 (GREEN 0장도 허용).' },
];

const IMMEDIATE_FAIL_TYPES = new Set([
  'colorCountExact', 'colorCountExactMulti', 'numberCountExact', 'numberCountExactMulti',
  'noTricksInRange', 'noTricksAtAll', 'neverConsecutiveTricks',
  'winOnlyTrick', 'neverLeadWithSuits', 'submarineCountExact', 'submarineExactAndOnly',
  'trickCountMoreThanCaptain', 'trickCountFewerThanCaptain',
  'winExactlyNTricks',
]);

const EARLY_SUCCESS_TYPES = new Set([
  'acquireSpecificCard', 'acquireMultipleSpecificCards', 'acquireAllOfNumber',
  'winSpecificTrick', 'winTricks',
  'acquireAtLeastOfNumber', 'colorCountAtLeast', 'acquireAtLeastOnePerColorAll', 'acquireFullRunOneColor',
  'trickContainsColorValue', 'trickAllColorValuesUnder', 'trickAllColorValuesOver',
  'winningCardCapturesCard', 'trickContainsCountOfNumber', 'trickAllValuesEven', 'trickAllValuesOdd',
  'trickColorSumOver', 'trickColorSumUnder', 'trickColorSumIn', 'winSubmarineTrickWithCard',
  'colorCountEqualInSingleTrick',
  'consecutiveAtLeast',
]);

export { TASKS, IMMEDIATE_FAIL_TYPES, EARLY_SUCCESS_TYPES };
